env:
  browser: true
  commonjs: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - never
  no-console:
    - warn
