tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "bat"
brew "coreutils"
brew "deno"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "imagemagick"
brew "lua-language-server"
brew "m-cli"
brew "mas"
brew "moreutils"
brew "neovim"
brew "pidof"
brew "pstree"
brew "pure"
brew "ripgrep"
brew "rust"
brew "shellcheck"
brew "stow"
brew "tldr"
brew "trash"
brew "tree"
brew "utimer"
brew "volta"
brew "zsh-completions"
brew "speedtest-cli"

cask "figma"
cask "firefox-developer-edition"
cask "font-iosevka"
cask "hammerspoon"
cask "iterm2"
cask "karabiner-elements"
cask "bitwarden"
cask "zoom"
cask "monitorcontrol"

# Personal
mas "Affinity Designer", id: 824171161
cask "affinity-publisher"
cask "affinity-photo"

# vim:ft=ruby
