#! /bin/bash

# Set iTerm profile by name
iterm2_profile() {
  echo -e "\033]50;SetProfile=$1\a"; clear;
}

# Set Terminal color by passing the arg `light` or `dark`
terminal_theme(){
    # Change iterm profile with time of day
    if [[ $(uname) == 'Darwin' ]]; then
        # Capitalize first letter
        type="$(tr '[:lower:]' '[:upper:]' <<< ${1:0:1})${1:1}"
        iterm2_profile "Sulphurpool-${type}"
    # else
        # printf string to set urxvt border color
    fi
    . ~/.config/base16-shell/base16-ateliersulphurpool.$1.sh
    export THEME=$1
}

# Colorize less
color_less(){
    # TODO: fix  issue when file doesn't have `lexer`
    pygmentize $1 | less -R
    less
}
