#!/usr/bin/env sh

brewfile=$(cat "$HOME/dotfiles/Brewfile")
first=true

# write a bundle of the current state to temp
cd /tmp || exit 1
brew bundle dump --force

# check the current state against what is actually managed in dotfiles
brew bundle list | while read -r installed; do
  substring=$(echo "$installed" | sed 's/\//\\\//g')
  if ! test "$(echo "$brewfile" | sed -n "/$substring/p")"; then
    $first && printf "\nInstalled but not in Brewfile:\n\n" && first=false
    echo "$installed"
  fi
done
