require("nvim-treesitter.configs").setup({
    ensure_installed = {
        "bash",
        "csv",
        "lua",
        "vim",
        "vimdoc",
        "query",
        "markdown",
        "markdown_inline",
        "css",
        "diff",
        "editorconfig",
        "git_config",
        "git_rebase",
        "go",
        "graphql",
        "html",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "luadoc",
        "luap",
        "regex",
        "ruby",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "svelte",
        "toml",
        "typescript",
        "xml",
        "yaml",
    },
    sync_install = false,
    highlight = {
        enable = true,
    },
    indent = { enable = true },
})
