#!/usr/bin/env zsh

alias g="git"
alias ls="ls -Gh"
alias mkdir="mkdir -p"
alias pomodoro="utimer -t 25s && say 'beep boop, times up'"
alias reload="source ~/.zshrc"
alias stow="stow --verbose --dotfiles"
alias vim="nvim"

# Set environment variables and run brew as the 'brewer' user with sudo.
# -H ensures we use brewer's $HOME directory, while -E keeps the current
# environment, so vars need to be passed in.
alias brew="sudo -E -H -u brewer brew"
alias brew_bundle="brew bundle --file=$HOME/dotfiles/Brewfile"

ql() {
  qlmanage -p "$1" &>/dev/null
}

ps_time() {
  pid=$(pgrep -i "$1")
  ps -p "$pid" -o etime=
}

# pom() {
#   utimer -c "$1" && say 'beep boop, times up' 
# }

theme() {
  case "$1" in
    'light')
      colorscheme="Catppuccin-Latte"
      FZF_DEFAULT_OPTS=" \
      --color=bg+:#ccd0da,bg:#eff1f5,spinner:#dc8a78,hl:#d20f39 \
      --color=fg:#4c4f69,header:#d20f39,info:#8839ef,pointer:#dc8a78 \
      --color=marker:#dc8a78,fg+:#4c4f69,prompt:#8839ef,hl+:#d20f39"
    ;;
    'midlight')
      colorscheme="Catppuccin-Frappe"
      FZF_DEFAULT_OPTS=" \
      --color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284 \
      --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf \
      --color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284"
    ;;
    'middark')
      colorscheme="Catppuccin-Macchiato"
      FZF_DEFAULT_OPTS=" \
      --color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
      --color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
      --color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796"
    ;;
    'dark')
      colorscheme="Catppuccin-Mocha"
      FZF_DEFAULT_OPTS=" \
      --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
      --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
      --color=marker:#f5e0dc,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
    ;;
    *)
      echo 'Themes options: light | midlight | middark | dark' >&MPL2
      return 1
    ;;
  esac

  # Used to set colorscheme in other tools like Neovim
  # vars need are be reexported since `kitty` does not export switching themes
  export TERM_COLORSCHEME=$colorscheme
  export BAT_THEME=$TERM_COLORSCHEME
  export FZF_DEFAULT_OPT
}
# Autocompletion
_theme() {
  compadd 'light' 'midlight' 'middark' 'dark'
}
compdef _theme theme

heic_to_jpg() {
  extension=${2##*.}
  echo $extension
  if [[ $extension != 'jpg' && $extension != 'jpeg' ]]; then
    echo "Error: extension must be 'jpg' or 'jpeg'"
  else
    sips -s format jpeg $1 --out $2
  fi
}

mov2mp4() {
    local filters=''
    local args=(-i "$1" -c:v libx264 -preset medium -crf 23 -c:a aac -b:a 192k -map_metadata -1 -movflags +faststart -async 1)
    if [[ "$2" == "-f" ]]; then
        local speedup_factor=$3
        local scale=$(bc <<< "scale=2; 1/$speedup_factor")
        filters='[0:v]setpts='"$scale"'*PTS[v];[0:a]atempo='"$speedup_factor"'[a]'
    fi
    if [[ -n "$filters" ]]; then
        args+=(-filter_complex "$filters" -map "[v]" -map "[a]")
    fi
    ffmpeg "${args[@]}" "${1:r}.mp4"
}

# vi:filetype=sh
