#! /bin/bash

# TODO seperate profile and alias settings into two different files
source ~/.bash_color
source ~/.bash_functions

# TODO move this to .bashrc?
# set theme based on time of day
hour=`date +"%H"`
if [ $hour -gt 7 ] && [ $hour -lt 16 ]; then
    terminal_theme light
else
    terminal_theme dark
fi

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion        # linux
[ -f ~/.git-completion.bash ] && source ~/.git-completion.bash    # mac

# Add git branches to PS1
[ -f ~/.git-prompt.sh ] && source ~/.git-prompt.sh

# Bold and color username@hostname in  yellow, working dir in blue, bang in yellow
# PS1="${debian_chroot:+($debian_chroot)}${BYellow}\u@\h: ${BBlue}\w${RESET} ${BYellow}\$${RESET} "
# TODO combine bash_colors with git_ps1
# export PS1="${BYellow}\u@\h: ${BBlue}\w$(__git_ps1 "(%s)"){RESET} ${BYellow}\$${RESET} "
export PS1='\[\e[33m\]\u@\h:\[\e[34m\]\W$(__git_ps1 "(%s)")\[\e[33m\]\$\[\e[m\] '

# Load local perl modules (perlbrew)
eval $(perl -I${HOME}/perl5/lib/perl5 -Mlocal::lib)
source ~/perl5/perlbrew/etc/bashrc

# make sublime default editor
# export EDITOR='open -a "Sublime Text"'

# look up system type
platform=$(uname)

######################
### LINUX SPECIFIC ###
######################
if [[ $platform == 'Linux' ]]; then

    # copy and pasting
    alias copy='xclip -selection c'
    alias paste='xclip -selection clipboard -o'

    #shorthand / easy to remember
    alias calc='bc'         # Calculator from terminal
    alias mouse='ltunify'   # Pair wireless mouse
    alias node='nodejs'
    alias fontr='fc-cache -f -v'

########################
### MAC OSX SPECIFIC ###
########################
elif [[ $platform == 'Darwin' ]]; then

    ## __HOMEBREW__ ##
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        source $(brew --prefix)/etc/bash_completion
    fi
    alias bup='brew update; brew upgrade'

    # Make GNU Coreutils default in OSX
    PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
    export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
    # make all homebrew packages accessible when prepended with 'my'
    # alias my="PATH=/usr/local/bin:$PATH"

    # aliases for Kwm tiling window manager
    alias kwm='brew services restart kwm'
    alias kstop='brew services stop kwm'

    # launch application
    alias finder='open .'
    alias thunar='finder'
    alias ps='open -a  /Applications/Adobe\ Photoshop\ CS5/Adobe\ Photoshop\ CS5.app'
    alias ai='open -a  /Applications/Adobe\ Illustrator\ CS5/Adobe\ Illustrator.app'
    alias graffle='open -a /Applications/OmniGraffle.app'
    alias chromium='open -a  /Applications/Chromium.app'
    alias firefox='open -a /Applications/Firefox.app'
    alias sublime='open -a /Applications/Sublime\ Text.app'
    alias writer='open -a /Applications/iA\ Writer.app'
    alias write='writer'

    alias cask='brew cask'
    alias todo='writer ~/Dropbox/notes/todo.md'
    alias nano='my nano'
    alias diff='colordiff'
fi

##########################
### UNIVERSAL  ALIASES ###
##########################

# Manual change Theme
alias light='terminal_theme light'
alias dark='terminal_theme dark'

# grep with color
alias grep='grep --color=auto'

# ls alias for color-mode
alias ls='ls --color'
alias lh='ls -lha'

# dir aliases
alias ll='ls -lhA'
alias la='ls -A'
alias l='ls -CF'
alias tr='tree -L '

# moving around dir
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../..'

# You can cry if you want to
alias rm='trash'

# refresh shell
# TODO difference between these two files?
# http://www.joshstaiger.org/archives/2005/07/bash_profile_vs.html
if [[ -s ~/.bash_profile ]]; then
  shell='source ~/.bash_profile'
  elif [[ -s ~/.bashrc ]]; then
    shell='source ~/.bashrc'
fi
alias reload=$shell

# Colorize cat
alias ccat="source-highlight --out-format=esc -o STDOUT -i"
alias subl='sublime'

# Git aliases
alias st='git status'
alias log='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias com='git commit'
alias patch='git add --patch'

# Actions
alias todo='sublime -n ~/Dropbox/notes/todo.md'   # Open ToDo list
alias md='vmd.sh'                                 # Read markdown files in Lynx
