#! /bin/bash

# Set iTerm titlebar text
iterm2_title() {
  echo -e "\033];$1\007"
}

# Set iTerm profile by name
iterm2_profile() {
  echo -e "\033]50;SetProfile=$1\a"; clear;

  # set terminal titlebar no text by default
  iterm2_title " "

  clear;
}

# Set Terminal color by passing the arg `light` or `dark`
terminal_theme(){
    # Change iterm profile with time of day
    if [[ $(uname) == 'Darwin' ]]; then
        # Capitalize first letter
        type="$(tr '[:lower:]' '[:upper:]' <<< ${1:0:1})${1:1}"
        iterm2_profile "Sulphurpool-${type}"
    # else
        # printf string to set urxvt border color
    fi
    . ~/.config/base16-shell/base16-ateliersulphurpool.$1.sh
    export THEME=$1
}

# Colorize less
color_less(){
    # TODO: fix  issue when file doesn't have `lexer`
    pygmentize $1 | less -R
    less
}

# Get process uptime
ps_time(){
  PID=$(pgrep -i $1)
  # TODO: if no PID, check pidof?
  [ ${#PID} -gt 0 ] && ps -o etime= -p $PID || exit 1 'no PID found'
}

# "TODAY'S WORKING FILE"
# Creates a new copy of the working file with
# today's date and opens it
#
# ARGUMENTS:
# $1: original file to be copied
# $2: if supplied, the new project_name

# Note: supplied filename *must* follow this naming convention
# client_marker : 2 character abbreviation for client
# date          : 4 character date (should be in MMDD format)
# project_name  : any number of characters used to express the
#		  filename and the project type

twf () {
  dir=$(dirname $1)
  filename=$(basename $1)
  client_marker=${filename/${filename:2}}
  today=$(date +%m%d)

  if [ -z $2 ];then
    project_name=${filename/${filename:0:6}}
  else
    project_name=$2
  fi

  new_file="$dir/${client_marker}${today}${project_name}"

  cp -v $1 $new_file
  open $new_file
}
